### ISSUE TITLE
Sensu - Alerta integration for v5 of alerta

### ISSUE THREAD

**Issue by francopeapea** [alerta/sensu-alerta#4]
Is this still working for v5? I see configuration loaded in sensu but nothing showing up in Alerta and no error logs

**Comment by francopeapea** [comment]
It's any chance to send the sslverify option in the json? It's not working that option right now and if you use alerta in https mode it gives you OpenSSL::SSL::SSLError

**Comment by satterly** [comment]
There needs to be done work done to update this to support sslverify but it should work with v5 for now. Can you add debug print statements to the ruby to work out what's going wrong?

**Comment by francopeapea** [comment]
This is the output for the sensu-server log

```
{"timestamp":"2018-07-13T12:37:51.358902+0000","level":"error","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/alerta.rb","name":"alerta"},"event":{"id":"4060c7ae-0dd2-4488-a6b8-5c7b23dfa081"},"output":["/opt/sensu/embedded/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/net/http.rb:948:in `connect'\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/net/http.rb:887:in `do_start'\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/net/http.rb:876:in `start'\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/net/http.rb:1407:in `request'\n\tfrom /usr/local/bundle/gems/httparty-0.16.2/lib/httparty/request.rb:143:in `perform'\n\tfrom /usr/local/bundle/gems/httparty-0.16.2/lib/httparty.rb:563:in `perform_request'\n\tfrom /usr/local/bundle/gems/httparty-0.16.2/lib/httparty.rb:505:in `post'\n\tfrom /usr/local/bundle/gems/httparty-0.16.2/lib/httparty.rb:605:in `post'\n\tfrom /etc/sensu/handlers/alerta.rb:75:in `block in handle'\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/timeout.rb:108:in `timeout'\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/timeout.rb:122:in `timeout'\n\tfrom /etc/sensu/handlers/alerta.rb:74:in `handle'\n\tfrom /usr/local/bundle/gems/sensu-plugin-2.5.0/lib/sensu-handler.rb:77:in `block in <class:Handler>'\nhttps://example.org:9002/api\n"]}
```

**Comment by francopeapea** [comment]
any posible thing to do in the meantime?

**Comment by francopeapea** [comment]
I'm using the nginx provided inside the container, modifying the nginx.conf , so I'm already using https but I'm not able to use this integration if I cannot send the sslverify option

**Comment by satterly** [comment]
I'd use a separate container to proxy the http-https traffic from sensual to alerta. 

Or just modify the ruby code to turn off SSL verification.

**Comment by satterly** [comment]
Isn't the endpoint for docker `POST /api/alert`?

**Comment by francopeapea** [comment]
I can confirm this, and the plugin still working with alerta v5. I'm going to close this issue

**Comment by satterly** [comment]
Great. Good work. :+1:
